// Utility for handling AI Creations (specialized content generated by the model)

// Creation types supported by the application
export type CreationType = 
  | 'code'         // Any programming language with syntax highlighting
  | 'markdown'     // Formatted text documents 
  | 'html'         // HTML content (already supported via htmlPreview)
  | 'svg'          // SVG graphics
  | 'mermaid'      // Mermaid diagrams (flowcharts, sequence diagrams, etc.)
  | 'react'        // React components
  | 'placeholder'  // For placeholder images with specified dimensions

// Interface for Creation data
export interface Creation {
  type: CreationType;
  content: string;
  title?: string;
  language?: string; // For code blocks
  metadata?: Record<string, unknown>; // Additional data specific to certain creation types
  id?: string; // Unique identifier for the creation
  externalDependencies?: Record<string, string>; // External dependencies for React components
}

// Custom event for showing a Creation
export type ShowCreationEvent = CustomEvent<Creation>;
export type ShowCreationSidebarEvent = CustomEvent<Creation>;

// Declare the event for TypeScript
declare global {
  interface WindowEventMap {
    'show-creation': ShowCreationEvent;
    'show-creation-modal': CustomEvent<Creation>;
    'show-creation-sidebar': ShowCreationSidebarEvent;
    // Add new events for streaming creations
    'stream-to-creation': CustomEvent<{content: string, creationId: string}>;
    'switch-creation-code': CustomEvent<{creationId: string}>;
    'switch-creation-preview': CustomEvent<{creationId: string}>;
    // Add new event for switching between creations
    'switch-creation': CustomEvent<Creation>;
    // Add new event for updating creation during streaming (without closing window)
    'stream-creation-update': CustomEvent<Creation>;
  }
}

// Helper function to show a Creation from anywhere
export function showCreation(creation: Creation): void {
  // Use the new event name that only the sidebar is listening for
  const event = new CustomEvent('show-creation-sidebar', {
    detail: creation
  });
  window.dispatchEvent(event);
}

// Helper function to switch from one creation to another with animation
export function switchCreation(creation: Creation): void {
  // Use the new event specifically for switching between creations
  const event = new CustomEvent('switch-creation', {
    detail: creation
  });
  window.dispatchEvent(event);
}

// Function to parse external dependencies from a string with format $$external$$ ... $$externalend$$
export function parseExternalDependencies(content: string): Record<string, string> | undefined {
  // Match the external dependencies block
  const externalMatch = /\$\$external\$\$([\s\S]*?)\$\$externalend\$\$/g.exec(content);
  
  if (!externalMatch || !externalMatch[1]) {
    return undefined;
  }
  
  try {
    // Attempt to parse as JSON
    const externalContent = externalMatch[1].trim();
    return JSON.parse(externalContent);
  } catch (error) {
    console.error('Failed to parse external dependencies:', error);
    return undefined;
  }
}

// Helper function to clean up triple backticks around creation blocks
function cleanTripleBackticksAroundCreations(content: string): string {
  // Track if we made any changes for logging
  const originalContent = content;
  
  // 1. Match pattern: ```<language>?\n$$creation: ... $$end$$ followed by ```
  // This handles the case where backticks wrap both the creation directive and the content
  let cleaned = content.replace(/```(\w*)\s*\n?\$\$creation:(\w+)(?:\s+([^\n]+))?\$\$([\s\S]*?)\$\$end\$\$\s*\n?```/g, 
    (_match, language, type, title, creationContent) => {
      // If there's a language specified in the backticks and not in the title, add it to the title
      if (language && title && !title.includes(':')) {
        return `$$creation:${type} ${language}:${title}$$${creationContent}$$end$$`;
      }
      // Otherwise just keep the title as is
      return `$$creation:${type} ${title || ''}$$${creationContent}$$end$$`;
    });
  
  // 2. Match pattern: ```<language>?\n$$creation: ... with no closing backticks yet
  // This is for streaming cases where the pattern is still being formed
  cleaned = cleaned.replace(/```(\w*)\s*\n?\$\$creation:(\w+)(?:\s+([^\n]+))?\$\$/g, 
    (_match, language, type, title) => {
      // If there's a language specified in the backticks and not in the title, add it to the title
      if (language && title && !title.includes(':')) {
        return `$$creation:${type} ${language}:${title}$$`;
      }
      // Otherwise just keep the title as is
      return `$$creation:${type} ${title || ''}$$`;
    });
    
  // 3. Match pattern: ...$$end$$\n``` - closing backticks right after end directive
  cleaned = cleaned.replace(/\$\$end\$\$\s*\n?```/g, '$$end$$');
  
  // 4. Special case for React components where jsx is in the backticks but missing in the title
  cleaned = cleaned.replace(/```jsx\s*\n?\$\$creation:react\s+([^:\n]+)\$\$/g, 
    '$$creation:react jsx:$1$$');
  
  // 5. Special case for Python code blocks
  cleaned = cleaned.replace(/```python\s*\n?\$\$creation:code\s+([^:\n]+)\$\$/g, 
    '$$creation:code python:$1$$');
  
  // Log any changes during development
  if (originalContent !== cleaned) {
    console.log('Cleaned triple backticks in creation block', {
      before: originalContent,
      after: cleaned
    });
  }
  
  return cleaned;
}

// Function to detect if a message contains a Creation directive
export function detectCreations(content: string): Creation[] {
  // First clean up any triple backticks around creation blocks
  const cleanedContent = cleanTripleBackticksAroundCreations(content);
  
  const creations: Creation[] = [];
  
  // Match pattern: $$creation:type [optional title]$$
  const creationPattern = /\$\$creation:(\w+)(?:\s+([^\n]+))?\$\$([\s\S]*?)\$\$end\$\$/g;
  
  let match;
  while ((match = creationPattern.exec(cleanedContent)) !== null) {
    // Destructure but ignore the full match
    const [, type, title, creationContent] = match;
    
    // Validate the type is supported
    const creationType = type.toLowerCase() as CreationType;
    if (!isValidCreationType(creationType)) {
      continue;
    }
    
    // Extract language and title for code blocks
    let language = undefined;
    let extractedTitle = title?.trim();
    
    if (creationType === 'code' && title && title.includes(':')) {
      const colonIndex = title.indexOf(':');
      language = title.substring(0, colonIndex).trim();
      // Extract title part after the colon (and any spaces)
      extractedTitle = title.substring(colonIndex + 1).trim();
    }
    
    // Create the creation object
    const creation: Creation = {
      type: creationType,
      content: creationContent.trim(),
      title: extractedTitle,
      language,
      id: `creation-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`
    };
    
    // If this is a React component, look for external dependencies
    if (creationType === 'react') {
      // Check if there's an external dependencies block that follows this creation
      // We need to look at content after this creation's end marker
      const endIndex = match.index + match[0].length;
      const remainingContent = cleanedContent.substring(endIndex);
      
      const externalDeps = parseExternalDependencies(remainingContent);
      if (externalDeps) {
        creation.externalDependencies = externalDeps;
      }
    }
    
    creations.push(creation);
  }
  
  return creations;
}

// Helper to validate creation types
function isValidCreationType(type: string): type is CreationType {
  return ['code', 'markdown', 'html', 'svg', 'mermaid', 'react', 'placeholder'].includes(type);
}

// Function to remove creation directives from content (to prevent duplicates)
export function removeCreationDirectives(content: string): string {
  // First clean up any triple backticks around creation blocks
  const cleanedContent = cleanTripleBackticksAroundCreations(content);
  
  // Remove $$creation:type ... $$end$$ blocks
  let result = cleanedContent.replace(/\$\$creation:(\w+)(?:\s+([^\n]+))?\$\$([\s\S]*?)\$\$end\$\$/g, '');
  
  // Also remove $$external$$ ... $$externalend$$ blocks
  result = result.replace(/\$\$external\$\$([\s\S]*?)\$\$externalend\$\$/g, '');
  
  return result;
} 